app/main/models.py
from app import db


adressobject_resident = db.Table(
    "adressobject_resident",
    db.Column("adressobject_id", db.Integer, db.ForeignKey("adress.id")),
    db.Column("resident_id", db.Integer, db.ForeignKey("resident.id")),
)


class Adress(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    country = db.Column(db.String(64), nullable=False)
    subject = db.Column(db.String(64), nullable=False)
    city = db.Column(db.String(64), nullable=False)
    index = db.Column(db.Integer, nullable=False)
    street = db.Column(db.String(64), nullable=False)
    number_building = db.Column(db.Integer, nullable=False)
    number_flat = db.Column(db.Integer, nullable=False)
    residents = db.relationship(
        "Resident",
        secondary=adressobject_resident,
        backref=db.backref("addresses", lazy="dynamic"),
    )


class Resident(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    second_name = db.Column(db.String(64), nullable=False)
    first_name = db.Column(db.String(64), nullable=False)
    middle_name = db.Column(db.String(64), nullable=True)

    def __repr__(self) -> str:
        return f"{self.second_name} {self.first_name} {self.middle_name}"

app/main/forms.py
from flask_babel import _
from flask_babel import lazy_gettext as _l
from flask_wtf import FlaskForm
from wtforms import IntegerField, SelectField, StringField, SubmitField
from wtforms_sqlalchemy.fields import QuerySelectMultipleField
from wtforms.validators import DataRequired

from app.main.models import Resident


class AdressForm(FlaskForm):
    country = StringField(_l("Страна"), validators=[DataRequired()])
    subject = StringField(_l("Регион"), validators=[DataRequired()])
    city = StringField(_l("Город"), validators=[DataRequired()])
    index = IntegerField(_l("Индекс"), validators=[DataRequired()])
    street = StringField(_l("Улица"), validators=[DataRequired()])
    number_building = IntegerField(_l("№ здания"), validators=[DataRequired()])
    number_flat = IntegerField(_l("№ квартиры"), validators=[DataRequired()])
    residents = QuerySelectMultipleField(
        "Житель", query_factory=lambda: Resident.query
    )
    submit = SubmitField(_l("Отправить"))


class ResidentForm(FlaskForm):
    second_name = StringField(_l("Фамилия"), validators=[DataRequired()])
    first_name = StringField(_l("Имя"), validators=[DataRequired()])
    middle_name = StringField(_l("Отчество"))
    submit = SubmitField(_l("Отправить"))
    

app/__init__.py
from flask import Flask
from flask_babel import Babel
from flask_babel import lazy_gettext as _l
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import Config

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = "auth.login"
login.login_message = _l("Пожалуйста, авторизуйтесь, чтобы увидеть эту страницу.")
babel = Babel()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    babel.init_app(app)

    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp

    app.register_blueprint(auth_bp, url_prefix="/auth")

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import models, routes

app/main/routes.py
# import random
# from faker import Faker
from flask import flash, redirect, render_template, request, url_for
from flask_babel import _
from sqlalchemy import or_

from app import db
from app.main import bp
from app.main.forms import AdressForm, ResidentForm
from app.main.models import Adress, Resident

# fake = Faker("ru-RU")


@bp.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    per_page = 20
    q = request.args.get("search", "")
    data = Adress.query.join(Resident, Resident.id == Adress.id)

    if q:
        data = data.filter(
            or_(
                Adress.country.like(f"%{q}%"),
                Adress.subject.like(f"%{q}%"),
                Adress.city.like(f"%{q}%"),
                Adress.index.like(f"%{q}%"),
                Adress.street.like(f"%{q}%"),
                Adress.number_building.like(f"%{q}%"),
                Adress.number_flat.like(f"%{q}%"),
                Resident.second_name.like(f"%{q}%"),    
                Resident.first_name.like(f"%{q}%"),
                Resident.middle_name.like(f"%{q}%"),
            )
        )

    data = data.paginate(page=page, per_page=per_page, error_out=False)

    if data.total == 0:
        return render_template(
            "main/index.html", title="index", data=data, pages=None
        )

    pages = data.iter_pages(
        left_edge=2, left_current=2, right_current=5, right_edge=2
    )
    return render_template(
        "main/index.html", title="index", data=data, pages=pages
    )


@bp.route("/create_address", methods=["GET", "POST"])
def create_address():
    form = AdressForm()
    if form.validate_on_submit():
        address = Adress(
            country=form.country.data,
            subject=form.subject.data,
            city=form.city.data,
            index=form.index.data,
            street=form.street.data,
            number_building=form.number_building.data,
            number_flat=form.number_flat.data,
            residents=form.residents.data,
        )
        db.session.add(address)
        db.session.commit()
        flash(_("Успешно! Адрес создан."))
        return redirect(url_for("main.index"))
    return render_template(
        "main/create_address.html",
        title=_("Добавить адрес"),
        form=form,
    )


@bp.route("/create_resident", methods=["GET", "POST"])
def create_resident():
    form = ResidentForm()
    if form.validate_on_submit():
        resident = Resident(
            second_name=form.second_name.data,
            first_name=form.first_name.data,
            middle_name=form.middle_name.data,
        )
        db.session.add(resident)
        db.session.commit()
        flash(_("Успешно! Житель зарегистрирован."))
        return redirect(url_for("main.index"))
    return render_template(
        "main/create_resident.html",
        title=_("Добавить жителя"),
        form=form,
    )


@bp.route("/edit")
def edit():
    page = request.args.get("page", 1, type=int)
    per_page = 20
    q = request.args.get("search", "")
    data = (
        Adress.query.join(Resident, Resident.id == Adress.id)
        .filter(
            or_(
                Adress.country.like(f"%{q}%"),
                Adress.subject.like(f"%{q}%"),
                Adress.city.like(f"%{q}%"),
                Adress.index.like(f"%{q}%"),
                Adress.street.like(f"%{q}%"),
                Adress.number_building.like(f"%{q}%"),
                Adress.number_flat.like(f"%{q}%"),
                Resident.second_name.like(f"%{q}%"),
                Resident.first_name.like(f"%{q}%"),
                Resident.middle_name.like(f"%{q}%"),
            )
        )
        .paginate(page=page, per_page=per_page, error_out=False)
    )
    pages = data.iter_pages(
        left_edge=2, left_current=2, right_current=5, right_edge=2
    )
    return render_template(
        "main/edit_list.html", title="Редактировать", data=data, pages=pages
    )


@bp.route("/edit/<int:address_id>", methods=["GET", "POST"])
def edit_id(address_id):
    form = AdressForm(obj=Adress.query.get(address_id))
    if request.method == "POST":
        if form.validate_on_submit():
            address = Adress(
                country=form.country.data,
                subject=form.subject.data,
                city=form.city.data,
                index=form.index.data,
                street=form.street.data,
                number_building=form.number_building.data,
                number_flat=form.number_flat.data,
                residents=form.residents.data,
            )
            db.session.add(address)
            db.session.commit()
            flash(_("Успешно! Адрес изменен."))
            return redirect(url_for("main.index"))

    return render_template(
        "main/edit_address.html",
        title=_("Добавить адрес"),
        form=form,
        address_id=address_id,
    )


@bp.route("/delete/<int:address_id>", methods=["GET", "POST"])
def delete_id(address_id):
    address = Adress.query.get(address_id)
    db.session.delete(address)
    db.session.commit()
    flash(_("Успешно! Адрес удален."))
    return redirect(url_for("main.index"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet"
              href="{{ url_for("static", filename="bootstrap/css/bootstrap.min.css") }}">
        <script scr="{{ url_for("static", filename="bootstrap/js/bootstrap.min.js") }}"></script>
        {% block scripts %}{% endblock %}
        <title>
            {% block title %}
                {% if title %}
                    {{ title }} - AdressBook
                {% else %}
                    {{ _('Welcome to AdressBook') }}
                {% endif %}
            {% endblock %}
        </title>
    </head>
    <main>
        <nav>
            {% include "includes/nav.html" %}
        </nav>
        <body>
            <div class="container">
                <!-- Flash-message -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-dismissible fade show {% if category == 'error' %}alert-danger{% elif category == 'warning' %}alert-warning{% else %}alert-success{% endif %}"
                                 role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
            <!-- Content -->
            {% block content %}Block 'content'{% endblock %}
        </body>
        <footer>
            {% include "includes/footer.html" %}
        </footer>
    </main>
</html>

app/templates/includes/footer.html
<footer class="page-footer font-small bg-light">
    <div class="footer-copyright text-center py-3">
        © 2023 Copyright:
        <a href="#">@Find me!</a>
    </div>
</footer>

app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Find me!</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {% if current_user.is_admin %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for("main.create_address") }}">Добавить адрес<span class="sr-only">(current)</span></a
              >
            </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for("main.create_resident") }}">Добавить жителя<span class="sr-only">(current)</span></a
              >
            </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for("main.edit") }}" }}">Редактировать<span class="sr-only">(current)</span></a
              >
            </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Удалить<span class="sr-only">(current)</span></a
              >
            </li>
          {% endif %}
          <!-- <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li> -->
        </ul>
        <form action="{{ url_for('main.index') }}"
              method="GET"
              class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2"
                 type="text"
                 name="search"
                 placeholder="Найдет всех"
                 aria-label="Search"/>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
        </form>
      </div>
      {% if current_user.is_authenticated %}
        <a href='{{ url_for("auth.logout") }}'
           class="btn btn-outline-primary my-2 my-sm-0 ml-2">Выйти</a
          >
        {% else %}
          <a href='{{ url_for("auth.login") }}'
             class="btn btn-outline-primary my-2 my-sm-0 ml-2">Войти</a
            >
          {% endif %}
        </div>
      </nav>

app/templates/main/create_address.html
{% extends 'base.html' %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for("static", filename="jquery/js/jquery-3.6.0.min.js") }}"></script>
    <link href="{{ url_for("static", filename="select2/css/select2.min.css") }}"
          rel="stylesheet"/>
    <script src="{{ url_for("static", filename="select2/js/select2.min.js") }}"></script>
    <script>
    $(document).ready(function() {
      $('.select2').select2({
        placeholder: 'Выберите жителей',
        allowClear: true
      });
    });
    </script>
{% endblock scripts %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Добавить адрес</h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.country.label(class="form-label") }}
                <br>
                {{ form.country(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.subject.label(class="form-label") }}
                <br>
                {{ form.subject(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.city.label(class="form-label") }}
                <br>
                {{ form.city(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.index.label(class="form-label") }}
                <br>
                {{ form.index(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.street.label(class="form-label") }}
                <br>
                {{ form.street(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.number_building.label(class="form-label") }}
                <br>
                {{ form.number_building(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.number_flat.label(class="form-label") }}
                <br>
                {{ form.number_flat(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.residents.label(class="form-label") }}
                <br>
                {{ form.residents(size=32, class="form-control select2") }}
            </p>
            <p>{{ form.submit(class="btn btn-success") }}</p>
        </form>
    </div>
{% endblock content %}

app/templates/main/create_resident.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Добавить адрес</h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.second_name.label(class="form-label") }}
                <br>
                {{ form.second_name(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.first_name.label(class="form-label") }}
                <br>
                {{ form.first_name(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.middle_name.label(class="form-label") }}
                <br>
                {{ form.middle_name(size=32, class="form-control") }}
            </p>
            <p>{{ form.submit(class="btn btn-success") }}</p>
        </form>
    </div>
{% endblock content %}

app/templates/main/edit_address.html
{% extends 'base.html' %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for("static", filename="jquery/js/jquery-3.6.0.min.js") }}"></script>
    <link href="{{ url_for("static", filename="select2/css/select2.min.css") }}"
          rel="stylesheet"/>
    <script src="{{ url_for("static", filename="select2/js/select2.min.js") }}"></script>
    <script>
    $(document).ready(function() {
      $('.select2').select2({
        placeholder: 'Выберите жителей',
        allowClear: true
      });
    });
    </script>
{% endblock scripts %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Редактировать адрес</h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.country.label(class="form-label") }}
                <br>
                {{ form.country(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.subject.label(class="form-label") }}
                <br>
                {{ form.subject(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.city.label(class="form-label") }}
                <br>
                {{ form.city(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.index.label(class="form-label") }}
                <br>
                {{ form.index(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.street.label(class="form-label") }}
                <br>
                {{ form.street(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.number_building.label(class="form-label") }}
                <br>
                {{ form.number_building(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.number_flat.label(class="form-label") }}
                <br>
                {{ form.number_flat(size=32, class="form-control") }}
            </p>
            <p>
                {{ form.residents.label(class="form-label") }}
                <br>
                {{ form.residents(size=32, class="form-control select2") }}
            </p>
            <p>{{ form.submit(class="btn btn-success") }}</p>
        </form>
        <form action="post">
            <a href="{{ url_for("main.delete_id", address_id=address_id)}}" class="btn btn-danger">Удалить
            </a>
        </form>
    </div>
{% endblock content %}

app/templates/main/edit_list.html
{% extends 'base.html' %}
{% block content %}
    {# Table #}
    <div class="container">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Редактировать</th>
                    <th scope="col">Страна</th>
                    <th scope="col">Субъект</th>
                    <th scope="col">Город</th>
                    <th scope="col">Индекс</th>
                    <th scope="col">Улица</th>
                    <th scope="col">№ здания</th>
                    <th scope="col">№ квартиры</th>
                    <th scope="col">Житель</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in data %}
                    <tr>
                        <td>
                            <a href="{{ url_for("main.edit_id", address_id=obj.id) }}">{{ obj.id }}</a>
                        </td>
                        <td>{{ obj.country }}</td>
                        <td>{{ obj.subject }}</td>
                        <td>{{ obj.city }}</td>
                        <td>{{ obj.index }}</td>
                        <td>{{ obj.street }}</td>
                        <td>{{ obj.number_building }}</td>
                        <td>{{ obj.number_flat }}</td>
                        <td>
                            {% for obj in obj.residents %}{{ obj }}{% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {# Pagination #}
    {% if data.pages > 1 %}
        <nav>
            <ul class="pagination justify-content-center">
                {% if data.has_prev %}
                    <li class="page-item">
                        <a href="{{ url_for('main.index', page=data.prev_num) }}"
                           class="page-link">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&laquo;</span>
                    </li>
                {% endif %}
                {% for num in pages %}
                    {% if num %}
                        {% if data.page == num %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a href="{{ url_for('main.index', page=num) }}" class="page-link">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% elif num is none %}
                        <li class="page-item disabled">
                            <span class="page-link dots">...</span>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if data.has_next %}
                    <li class="page-item">
                        <a href="{{ url_for('main.index', page=data.next_num) }}"
                           class="page-link">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&raquo;</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% block content %}
    {# Table #}
    <div class="container">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Страна</th>
                    <th scope="col">Субъект</th>
                    <th scope="col">Город</th>
                    <th scope="col">Индекс</th>
                    <th scope="col">Улица</th>
                    <th scope="col">№ здания</th>
                    <th scope="col">№ квартиры</th>
                    <th scope="col">Житель</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in data %}
                    <tr>
                        <td>{{ obj.country }}</td>
                        <td>{{ obj.subject }}</td>
                        <td>{{ obj.city }}</td>
                        <td>{{ obj.index }}</td>
                        <td>{{ obj.street }}</td>
                        <td>{{ obj.number_building }}</td>
                        <td>{{ obj.number_flat }}</td>
                        <td>
                            {% for resident in obj.residents %}{{ resident }}</br>{% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {# Pagination #}
    {% if data.pages > 1 %}
        <nav>
            <ul class="pagination justify-content-center">
                {% if data.has_prev %}
                    <li class="page-item">
                        <a href="{{ url_for('main.index', page=data.prev_num) }}"
                           class="page-link">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&laquo;</span>
                    </li>
                {% endif %}
                {% for num in pages %}
                    {% if num %}
                        {% if data.page == num %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a href="{{ url_for('main.index', page=num) }}" class="page-link">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% elif num is none %}
                        <li class="page-item disabled">
                            <span class="page-link dots">...</span>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if data.has_next %}
                    <li class="page-item">
                        <a href="{{ url_for('main.index', page=data.next_num) }}"
                           class="page-link">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&raquo;</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}